/**********************************************************************
*
*   Component hook generated by Quest
*
*   Code Logic for the component goes in this hook
*   To setup bindings that use the data here or call the functions here, use the Quest editor   
*
*   For help and further details refer to: https://www.quest.ai/docs
*
*
**********************************************************************/

const useFrame1 = () => {
  let data: any = {};
  const onClick = (): any => {};
  const close = (): any => {};

  let fns: any = {onClick, close};
  return {data, fns};
}

export default useFrame1;